import type { TemplateItem } from "../types";

export const TEMPLATES: TemplateItem[] = [
  {
    id: "t1",
    name: "Waiting for a waffle o'clock",
    thumbnail: "",
    width: 1080,
    height: 1080,
    nodes: [
      {
        id: "n1",
        type: "rect",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#fef3c7",
      },
      {
        id: "n2",
        type: "text",
        x: 80,
        y: 400,
        width: 920,
        height: 120,
        text: "Waiting for a waffle o'clock",
        fontSize: 64,
        fontFamily: "sans-serif",
        fill: "#92400e",
      },
    ],
  },
  {
    id: "t2",
    name: "VIBES VIBES VIBES",
    thumbnail: "",
    width: 1080,
    height: 1080,
    nodes: [
      {
        id: "n1",
        type: "rect",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#fde047",
      },
      {
        id: "n2",
        type: "text",
        x: 80,
        y: 400,
        width: 920,
        height: 200,
        text: "VIBES VIBES VIBES",
        fontSize: 96,
        fontFamily: "sans-serif",
        fill: "#166534",
      },
    ],
  },
  {
    id: "t3",
    name: "Thanksgiving Dinner",
    thumbnail: "",
    width: 1080,
    height: 1080,
    nodes: [
      {
        id: "n1",
        type: "rect",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#d6d3d1",
      },
      {
        id: "n2",
        type: "text",
        x: 80,
        y: 300,
        width: 920,
        height: 200,
        text: "YOU ARE INVITED! THANKS GIVING DINNER",
        fontSize: 48,
        fontFamily: "sans-serif",
        fill: "#44403c",
      },
    ],
  },
  {
    id: "t4",
    name: "Create your own SUNSHINE",
    thumbnail: "",
    width: 1080,
    height: 1080,
    nodes: [
      {
        id: "n1",
        type: "rect",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fill: "#93c5fd",
      },
      {
        id: "n2",
        type: "text",
        x: 80,
        y: 380,
        width: 920,
        height: 180,
        text: "Create your own SUNSHINE\nHave a great day!",
        fontSize: 56,
        fontFamily: "sans-serif",
        fill: "#1e3a8a",
      },
    ],
  },
  {
    id: "t5",
    name: "Blank",
    thumbnail: "",
    width: 1080,
    height: 1080,
    nodes: [],
  },
];
